import type { Metadata } from "next";
import localfont from 'next/font/local'
import "./globals.css";

export const metadata: Metadata = {
  title: "Southborn",
  description: "Generated by create next app",
};

const Bebas = localfont({
  src : './Fonts/BebasNeue-Regular.ttf',
  variable : '--font-bebas'
})

const Inter = localfont({
  src : './Fonts/Inter-VariableFont_opsz,wght.ttf',
  variable : '--font-inter'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${Bebas.variable} ${Inter.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
